var myFullName;
console.log(myFullName);
myFullName="Neha Newase";
console.log(myFullName);
myFullName="Neha Shubham Newase";
console.log(myFullName);
var myLove="I Love Only JS";
console.log(myLove);
var firstName="Neha";
var lastName="Newase";
var age="28";
var address="Pune";
var pincode="411047";
var gender="Female";
var isMarried="True";
console.log("My First Name =", firstName);
console.log("My Last Name =", lastName);
console.log("My age =", age);
console.log("My address =", address);
console.log("My pincode =", pincode);
console.log("My gender =", gender);
console.log("Marriage status =", isMarried);
